module.exports = {
    LOCALE: {
        DEFAULT: "en-US",
    },
    INTERACTIONS: {
        SLASH: false,
        CONTEXT: false,
        GLOBAL: false,
        TEST_GUILD_ID: "",
    },
    DASHBOARD: {
        ENABLED: true,
        ENCRYPT: true,
        LOGO_NAME: "Strange",
    },
    SUPPORT_SERVER: "https://discord.gg/abc123",
    PLUGINS: [
        "core",
        "anime",
        "automod",
        "autorole",
        "counter",
        "economy",
        "fun",
        "giveaways",
        "greeting",
        "guild-logger",
        "image",
        "information",
        "invites",
        "moderation",
        "music",
        "owner",
        "presence",
        "reaction-roles",
        "social",
        "stats",
        "suggestion",
        "ticket",
        "translation",
        "utility",
    ],
};
